### ISSUE TITLE
Vietnam is spelled Viet Nam which is wrong

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtecharchive/tf-map#1]
related issue: https://github.com/threefoldtech/tfgrid_dashboard/issues/152

**Comment by MohamedElmdary** [comment]
Fixed the issue by creating a map with the correct names
Note: wrong names came from https://unpkg.com/world-atlas@1.1.4/world/110m.json which is used to draw the entire map itself

**Comment by khaledyoussef24** [comment]
when it will be reflected on the map?
thereis a space between Viet and Nam
this is from devnet
![Screenshot from 2022-08-22 10-07-49](https://user-images.githubusercontent.com/110984055/185871813-b0a48ca0-9acc-4d4d-9deb-4dec0cebe996.png)

**Comment by khaledyoussef24** [comment]
##verified on devnen
![Screenshot from 2022-08-23 13-49-20](https://user-images.githubusercontent.com/110984055/186360512-531686ae-ccea-46ea-9834-8c6a7bb987ab.png)
